version: '3.3'
services:
  deployjs:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'deployjs'
      MYSQL_USER: 'nk'
      MYSQL_PASSWORD: 'nikol@us06'
      MYSQL_ROOT_PASSWORD: 'YTkJx7agFHW745'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/.MySQLData/mysqlonly/deployjs:/var/lib/mysql
